config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id if current_user
    @comment.save
    # you need to save the comment
    #you get the post and then create a comment allowing a comment
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end


  def update
    #so if we have clicked the button to update,
    #then update else you are still editing
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only:[:show, :edit, :update, :destroy]
  # do th find post method only for those methods
  before_action :authenticate_user!, except: [:index, :show]
  # what this is doing, routes you to the login page before you can
  # create a post. The only places you can go is show and index
  # otherwise you have to login

  #show all the posts
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # user arrives at this page
  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  # if we create a post and able to save
  # then redirect to the post show page
  # else you render to new
  # click button to save with set params
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    #so if we have clicked the button to update,
    #then update else you are still editing
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
      @post = Post.find(params[:id])
  end
  # needs a post and allows a title/content
  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment
  .content
    %p= comment.comment
    %p= comment.user.email
  .buttons
    = link_to "Edit", edit_post_comment_path(comment.post, comment)
    = link_to "Delete Reply", [comment.post, comment], method: :delete, data: {confirm: "Are you Sure?"}
-# so the method: asks for which method to do
-# the data is the pop up for what will happen
-# the [] is
-# for edit, we are grabbing the comment.post and the comment

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :comment
  = f.submit
-# comment is build from post, but we want user id

app/views/comments/edit.html.haml
%h1 Edit Comment


= simple_form_for([@post, @comment]) do |f|
  = f.input :comment
  = f.submit
= link_to 'Cancel', post_path(@post)
-# you don't want the build because it will build a new comment
-# this @post.comments.build will say to build the comment for the post
  

app/views/layouts/application.html.haml
!!!
<!- yield signals where the view will be at ->
%html
%head
  %title Mobile-Friendly Forum
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header.main_header
    #logo
      %p Mobile-Friendly Forum
    #buttons
      - if user_signed_in?
        = link_to "New Post", new_post_path
      - else
        = link_to "Sign Up",  new_user_registration_path
        = link_to "Sign In",  new_user_session_path
  .container
    %p.notice= notice
    %p.alert= alert

  .container
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.submit

app/views/posts/_forms.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.submit

app/views/posts/edit.html.haml
%h1 Edit Post


= render 'form'

=link_to 'Cancel', post_path

app/views/posts/index.html.haml
- @posts.each do |post|
  %h2= link_to post.title, post
  %p
    Published at
    = time_ago_in_words(post.created_at)
    by
    = post.user.email
-# we need to add the feature of replying to comments
-# upvotes and downvotes
-# idk

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml

%h1= @post.title
%p= @post.content

#comments
  #h2
    = @post.comments.count
    Comments
  = render @post.comments.order('created_at DESC')

  %h3 Reply to thread
  = render "comments/form"

= link_to "Edit", edit_post_path(@post)
= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Do you want to delete this?"}
= link_to "Home", root_path
-# link_to creates a link and edit_post_path does the method
-# look up more into the delete part
-# you pass the route as the first argument
-# :method and :data-confirm are HTML5 attributes
-# method attribute says what REST call is being dong aka delete